# Generated by Django 5.0.6 on 2024-06-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
