# Generated by Django 5.0.6 on 2024-06-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctor_dni_paciente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fecha_nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
    ]
