# Generated by Django 5.0.6 on 2024-06-30 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_doctor_direccion_doctor_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
    ]
