# Generated by Django 5.0.6 on 2024-08-19 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_doctor_user_paciente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/reportes/')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Home.reporte')),
            ],
        ),
    ]
